# Metadata about this component, to be used in the CMS
spec:
  structures:
    - editorial_blocks
  label: "Call Out"
  description: An information, warning, or error message
  icon: info
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  type: info
  editorials: [bookshop:structure:editorial_blocks!(generic/textBlock)]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  type:
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - id: info
          name: Information
        - id: warning
          name: Warning
        - id: error
          name: Error
